### ISSUE TITLE
Polyfill is confusing

### ISSUE THREAD

**Issue by evilpie** [tc39/proposal-item-method#17]
`// No need to clamp to within the length, as .slice() does;` What does this comment have to do with the code?

Maybe this polyfill should closely follow the spec instead.

**Comment by tabatkins** [comment]
It's a comment about why it intentionally diverges from how .slice()'s spec works, which might be surprising given the overall similarity of the behavior.

> Maybe this polyfill should closely follow the spec instead.

It does.

**Comment by evilpie** [comment]
It doesn't check if index > length.

**Comment by ljharb** [comment]
@evilpie https://npmjs.com/array.prototype.item and https://npmjs.com/string.prototype.item do have those steps, at least ;-)

**Comment by tabatkins** [comment]
Yeah, you were right, it's fixed now.
