### ISSUE TITLE
What is “squooshgate”?

### ISSUE THREAD

**Issue by ExE-Boss** [tc39/proposal-item-method#24]
“squooshgate” is mentioned in the **README.md**:
<https://github.com/tc39/proposal-item-method/blob/069255c7c365eda9aeeaaabeba12eb38b823dc31/README.md#L88>

But there’s no explanation of what it is/was.

**Comment by bakkot** [comment]
Pretty sure that should be ["smooshgate"](https://developers.google.com/web/updates/2018/03/smooshgate).
